auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

admins:
    type:     rest
    resource: AppBundle\Controller\AdminController

selfUser:
    type:     rest
    resource: AppBundle\Controller\UserController

users:
    type:     rest
    resource: AppBundle\Controller\selfUserController

userRoles:
    type:     rest
    resource: AppBundle\Controller\UserRoleController

companyTypes:
    type:     rest
    resource: AppBundle\Controller\CompanyTypeController

companies:
    type:     rest
    resource: AppBundle\Controller\CompanyController