auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

admins:
    type:     rest
    resource: AppBundle\Controller\AdminController

selfUser:
    type:     rest
    resource: AppBundle\Controller\UserController

companyTypes:
    type:     rest
    resource: AppBundle\Controller\CompanyTypeController

companies:
    type:     rest
    resource: AppBundle\Controller\CompanyController

folders:
    type:     rest
    resource: AppBundle\Controller\FolderController

userRoles:
    type:     rest
    resource: AppBundle\Controller\UserRoleController

users:
    type:     rest
    resource: AppBundle\Controller\selfUserController

accessTypes:
    type:     rest
    resource: AppBundle\Controller\AccessTypeController

docs:
    type:     rest
    resource: AppBundle\Controller\DocController
