AppBundle\Document\Folder:
    exclusion_policy: none
    properties:
        id:
            groups: ['folders', 'folder', 'postFolder']
        name:
            groups: ['folders', 'folder', 'postFolder', 'postDoc', 'docs', 'doc']
        accesses:
            groups: ['folder', 'postFolder', 'docs', 'doc']
        companies:
            groups: ['postFolder', 'postDoc']
        docs:
            groups: ['folder']
        createdBy:
            groups: ['folder', 'postFolder']
        createdAt:
            groups: ['folder', 'postFolder']
        updatedBy:
            groups: ['folders', 'folder']
        updatedAt:
            groups: ['folders', 'folder']