AppBundle\Document\Company:
    exclusion_policy: none
    properties:
        id:
            groups: ['companies', 'company', 'postCompany',
                'user',
                'adminUserCompany',
                'folder', 'postFolder']
        name:
            groups: ['companies', 'company', 'postCompany',
                'user',
                'adminUserCompany',
                'folder', 'postFolder']
        address:
            groups: ['companies', 'company', 'postCompany',
                'user',
                'folder', 'adminUserCompany']
        companyType:
            groups: ['companies', 'company', 'postCompany',
                'user',
                'adminUserCompany',
                'folder']
        users:
            groups: ['company']
        folders:
            groups: ['company']
        createdBy:
            groups: ['companies', 'company', 'postCompany']
        createdAt:
            groups: ['companies', 'company', 'postCompany']
        updatedBy:
            groups: ['companies', 'company']
        updatedAt:
            groups: ['companies', 'company']