AppBundle\Document\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['users', 'user', 'postUser',
                'companies', 'company',
                'auth-token',
                'adminUserCompany',
                'self',
                'accessType',
                'postFolder']
        firstName:
            groups: ['users', 'user', 'postUser',
                'companies', 'company',
                'auth-token',
                'adminUserCompany',
                'self',
                'accessType',
                'postFolder', 'folder']
        lastName:
            groups: ['users', 'user', 'postUser',
                'companies', 'company',
                'auth-token',
                'adminUserCompany',
                'self',
                'accessType',
                'postFolder', 'folder']
        email:
            groups: ['users', 'user', 'postUser',
                'companies', 'company',
                'auth-token',
                'adminUserCompany',
                'self',
                'accessType']
        plainPassword:
            groups: ['postUser', 'adminUserCompany']
        userRole:
            groups: ['users', 'user', 'postUser',
                'companies', 'company',
                'auth-token',
                'adminUserCompany',
                'self',
                'accessType']
        companies:
            groups: ['user',
                'adminUserCompany']
        createdBy:
            groups: ['user', 'postUser',
                'self']
        createdAt:
            groups: ['user', 'postUser',
                'self']
        updatedBy:
            groups: ['user', 'postUser',
                'self']
        updatedAt:
            groups: ['user', 'postUser',
                'self']