AppBundle\Document\Company:
    exclusion_policy: none
    properties:
        id:
            groups: ['companies', 'company', 'postCompany',
                'users', 'user', 'postUser',
                'adminUserCompany']
        name:
            groups: ['companies', 'company', 'postCompany',
                'users', 'user', 'postUser',
                'adminUserCompany']
        address:
            groups: ['companies', 'company', 'postCompany',
                'users', 'user', 'postUser',
                'adminUserCompany']
        companyType:
            groups: ['companies', 'company', 'postCompany',
                'users', 'user', 'postUser',
                'adminUserCompany']
        users:
            groups: ['company']
        folders:
            groups: ['company']
        createdBy:
            groups: ['companies', 'company', 'postCompany']
        createdAt:
            groups: ['companies', 'company', 'postCompany']
        updatedBy:
            groups: ['companies', 'company']
        updatedAt:
            groups: ['companies', 'company']